#ifndef MARISA_B_NATIVE_H
#define MARISA_B_NATIVE_H

#include <array>
#include <string>

#include "Common.h"

class PowerSpectrum;

namespace marisa_b_native {

struct Triangle {
    real k1 = 0.05;
    real k2 = 0.05;
    real mu12 = -0.5;
};

/*
 * Public Cartesian representation used by estimator-matched shell
 * projectors.  The three rows are the closed external wavevectors.  Keeping
 * this type independent of the internal Vec3 implementation avoids coupling
 * the native API to a particular vector helper while still retaining the
 * absolute orientation required by a Cartesian CIC reconstruction window.
 */
using ClosedTriangleVectors =
    std::array<std::array<real, 3>, 3>;

struct ComponentStats {
    real value = 0.0;
    real abserr = 0.0;
    int neval = 0;
};

struct ComponentResult {
    Triangle triangle;
    real k3 = 0.0;
    real Btree = 0.0;
    real B222 = 0.0;
    real B321I = 0.0;
    real B321II = 0.0;
    real B411 = 0.0;
    real Bloopterms = 0.0;
    real B1loop = 0.0;
    real Btotal = 0.0;
    real dBdfNL_local_tree = 0.0;
    real dBdfNL_local_B122I = 0.0;
    real dBdfNL_local_B122II = 0.0;
    real dBdfNL_local_B113I = 0.0;
    real dBdfNL_local_B113II = 0.0;
    /*
     * single-source local PNG 的 finite-fNL 严格一环二次系数：
     *
     *   B112II(fNL) = fNL^2 * B112II_fNL2_coefficient .
     *
     * 它不是 fNL=0 处的一阶导数。旧 Gaussian、response 与 diagnostic
     * 入口均不自动把它并入 Btotal；只有显式 finite-fNL 入口会按
     * fNL^2 * coefficient 组合完整 B(fNL)。
     */
    real B112II_fNL2_coefficient = 0.0;
    /*
     * bias-v1 PNG one-loop 使用与 Gaussian 基底相同的 diagram 命名。
     * 旧 matter-PNG 的 B122/B113 字段继续保留，二者不可混用或重命名。
     */
    real dBdfNL_local_B222 = 0.0;
    real dBdfNL_local_B321I = 0.0;
    real dBdfNL_local_B321II = 0.0;
    real dBdfNL_local_B411 = 0.0;
    real dBdfNL_local_1loop = 0.0;
    real dBdfNL_local_total = 0.0;
    real dBdfNL_local_primordial = 0.0;
    real dBdfNL_local_bphi_f2 = 0.0;
    real dBdfNL_local_bphi_advection = 0.0;
    real dBdfNL_local_bphidelta = 0.0;
    real dBdfNL_local_bphi_b2 = 0.0;
    real dBdfNL_local_bphi_bK2 = 0.0;
    real dBdfNL_local_bphi_reconstruction = 0.0;
    /*
     * 固定 renormalized bias 下，pre-reconstruction halo tree 的
     * finite-local-PNG 二次系数：
     *
     *   B_h,tree(fNL) = B_h,tree^G
     *                   + fNL dBdfNL_local_tree
     *                   + fNL^2 Bhalo_tree_fNL2_deterministic .
     *
     * 分量对应 Dizgah et al. (2020), arXiv:2010.14523, Eq. (2.58)。
     * `bphi_sq` 明确表示 bphi*bphi；`bphi2_operator` 表示独立的
     * phi^2 bias 系数 b_{phi^2}，两者不可混淆。
     */
    real Bhalo_tree_fNL2_bphi_B0 = 0.0;
    real Bhalo_tree_fNL2_bphi_sq_advection = 0.0;
    real Bhalo_tree_fNL2_bphi_sq_F2 = 0.0;
    real Bhalo_tree_fNL2_bphi_sq_b2 = 0.0;
    real Bhalo_tree_fNL2_bphi_sq_bK2 = 0.0;
    /*
     * Finite-R reconstruction contribution generated by the quadratic
     * product of the two scale-dependent K1 PNG responses.  This vanishes
     * continuously when the reconstruction shift is disabled.
     */
    real Bhalo_tree_fNL2_bphi_sq_reconstruction = 0.0;
    real Bhalo_tree_fNL2_bphi_bphidelta = 0.0;
    real Bhalo_tree_fNL2_bphi2_operator = 0.0;
    real Bhalo_tree_fNL2_deterministic = 0.0;
    /*
     * Eq. (2.65) 的 leading quadratic PNG stochastic raw basis：
     *
     *   bphi^2 sum_i P_L(k_i)/M(k_i)^2 .
     *
     * nbar 与 residual stochastic amplitude 仍由数据/profile 层加入。
     */
    real Bhalo_tree_fNL2_stochastic_alpha3PNG_basis = 0.0;
    real stochastic_alpha3_basis = 0.0;
    real stochastic_alpha4_basis = 1.0;
    real dBdfNL_stochastic_alpha3_basis = 0.0;
    ComponentStats B222_stats;
    ComponentStats B321I_stats;
    ComponentStats B411_stats;
    ComponentStats P13_k1_stats;
    ComponentStats P13_k2_stats;
    ComponentStats P13_k3_stats;
    ComponentStats P12_png_k1_stats;
    ComponentStats P12_png_k2_stats;
    ComponentStats P12_png_k3_stats;
    ComponentStats dBdfNL_local_B122I_stats;
    ComponentStats dBdfNL_local_B122II_stats;
    ComponentStats dBdfNL_local_B113I_stats;
    ComponentStats dBdfNL_local_B113II_stats;
    ComponentStats dBdfNL_local_1loop_stats;
    ComponentStats dBdfNL_local_total_stats;
    ComponentStats B112II_fNL2_coefficient_stats;
    ComponentStats dBdfNL_local_B222_stats;
    ComponentStats dBdfNL_local_B321I_stats;
    ComponentStats dBdfNL_local_B321II_stats;
    ComponentStats dBdfNL_local_B411_stats;
    ComponentStats dP13dfNL_local_k1_stats;
    ComponentStats dP13dfNL_local_k2_stats;
    ComponentStats dP13dfNL_local_k3_stats;
};

struct NativeConfig {
    real epsrel = 1.0e-3;
    real p13_epsrel = 1.0e-2;
    real epsabs = 1.0e-10;
    real qmin = 1.0e-4;
    real qmax = 30.0;
    /*
     * local primordial B0/T0 correlator 中每一条 P_phi propagator 的
     * 最小模长。它同时作用于 linear-fNL P12/B122II/B113II 的全部 B0
     * legs，以及 finite-fNL^2 B112II 的 external/exchange legs。与
     * loop-variable 的 qmin 分开保存，因为 collapsed channel
     * |q+k_i| -> 0 不会被单纯的 |q| >= qmin 排除。0 表示沿用 qmin。
     */
    real png_ir_cutoff = 0.0;
    /*
     * B112II 隔离路径可选的多中心低差异积分器。false 保留历史 adaptive
     * ReACT cubature；true 使用围绕全部 collapsed centers 的确定性
     * replicated Halton importance quadrature。
     */
    bool png_b112ii_multicenter_qmc = false;
    /*
     * post-reconstruction matter-PNG linear one-loop 的生产积分路径。
     * true 时 P12/B122II/B113II 分别围绕其全部 primordial/Gaussian
     * collapsed centers 使用与 B112II 相同的 deterministic replicated
     * Halton mixture quadrature。固定节点保证随 reconstruction
     * lambda=b1/b_rec_h 的低阶多项式不会被自适应分区噪声破坏。
     */
    bool png_linear_multicenter_qmc = false;
    int png_b112ii_qmc_power = 12;
    int png_b112ii_qmc_replicates = 4;
    real smoothing_radius = 10.0;
    real bias_recon = 1.0;
    real recon_cellsize = 0.0;
    int recon_cic_window_power = 0;
    real singular_floor = 1.0e-5;
    real ir_sigma2 = 0.0;
};

/* Auditable finite-box contract used by every local-primordial B0/T0 leg. */
real local_png_ir_cutoff(const NativeConfig& config);
bool local_png_primordial_triplet_is_resolved(
    real k1,
    real k2,
    real k3,
    const NativeConfig& config);

/*
 * Deterministic numerical-audit observable for the multicenter QMC measure.
 * It integrates unity over qmin<=|q|<=qmax after excising one shifted
 * spherical zero-mode region.  This is not a physical bispectrum component;
 * it exists so production builds can verify normalization, balance weights,
 * shifted-center routing, replicate errors, and exact evaluation counts
 * against an analytic volume.
 */
ComponentStats audit_local_png_multicenter_qmc_excision_volume(
    const std::array<real, 3>& shifted_center,
    real shifted_cutoff,
    const NativeConfig& config);

/*
 * halo bias-v1 的确定性参数。
 *
 * 这一结构只保存 bias functional 中的物理系数；alpha3/alpha4 与 nbar
 * 属于数据层的 stochastic 模板，不混入 loop kernel。这样可以让同一组
 * b1/b2/bK2 在 pre/post reconstruction 之间严格共享，也避免修改冻结的
 * dark-matter 模式。
 */
struct HaloBiasV1Params {
    real b1 = 1.0;
    real b2 = 0.0;
    real bK2 = 0.0;
    real bphi = 0.0;
    real bphidelta = 0.0;
    real bphi2 = 0.0;
};

real triangle_k3(const Triangle& tri);

real alpha(real k1, real k2, real mu);
real alphas(real k1, real k2, real mu);
real beta1(real k1, real k2, real mu);
real F2eds(real k1, real k2, real mu);
real G2eds(real k1, real k2, real mu);
real F3eds(real k1, real k2, real k3, real x23, real x12, real x13);
real G3eds(real k1, real k2, real k3, real x23, real x12, real x13);
real F3edsb(real k1, real k2, real k3, real k23, real k12, real k13, real x23, real x12, real x13);
real G3edsb(real k1, real k2, real k3, real k23, real k12, real k13, real x23, real x12, real x13);
real F4edsb(real k1, real k2, real k3, real k4, real x23, real x24, real x12, real x13, real x14);

ComponentStats P13_dd(const PowerSpectrum& P_L, real k, const NativeConfig& config);
ComponentResult compute_pre_recon_gaussian(const PowerSpectrum& P_L, const Triangle& tri, const NativeConfig& config);
ComponentResult compute_post_recon_gaussian(const PowerSpectrum& P_L, const Triangle& tri, const NativeConfig& config);
ComponentResult compute_pre_recon_halo_bias_v1_gaussian(
    const PowerSpectrum& P_L,
    const Triangle& tri,
    const NativeConfig& config,
    const HaloBiasV1Params& bias);
ComponentResult compute_post_recon_halo_bias_v1_gaussian(
    const PowerSpectrum& P_L,
    const Triangle& tri,
    const NativeConfig& config,
    const HaloBiasV1Params& bias);
ComponentResult compute_post_recon_gaussian_ir_nowiggle(
    const PowerSpectrum& P_L,
    const PowerSpectrum& P_nw,
    const Triangle& tri,
    const NativeConfig& config);
real local_png_tree_dfNL(const PowerSpectrum& P_L, const PowerSpectrum& transfer_m, const Triangle& tri, real b1 = 1.0);
ComponentResult compute_pre_recon_halo_bias_v1_local_png_tree_dfNL(
    const PowerSpectrum& P_L,
    const PowerSpectrum& transfer_m,
    const Triangle& tri,
    const HaloBiasV1Params& bias);
ComponentResult compute_post_recon_halo_bias_v1_local_png_tree_dfNL(
    const PowerSpectrum& P_L,
    const PowerSpectrum& transfer_m,
    const Triangle& tri,
    const NativeConfig& config,
    const HaloBiasV1Params& bias);
ComponentResult
compute_post_recon_halo_bias_v1_local_png_tree_dfNL_vectors(
    const PowerSpectrum& P_L,
    const PowerSpectrum& transfer_m,
    const ClosedTriangleVectors& vectors,
    const NativeConfig& config,
    const HaloBiasV1Params& bias);
/*
 * Shell-projectable basis for the extra linear-fNL response generated when
 * the reconstruction denominator is promoted from fixed b_rec to
 *
 *   b_rec(k; fNL_rec) = b_rec + fNL_rec b_phi_rec/M(k).
 *
 * At fNL_rec=0 the deterministic Gaussian tree contribution obeys
 *
 *   dB/dfNL_rec =
 *     b1^4 (b_phi_rec/b_rec)
 *     compute_post_recon_halo_local_png_brec_denominator_tree_basis_vectors.
 *
 * The basis contains only the derivative of the reconstruction denominator;
 * the ordinary fixed-b_rec halo-PNG response remains in ComponentResult.
 */
real
compute_post_recon_halo_local_png_brec_denominator_tree_basis_vectors(
    const PowerSpectrum& P_L,
    const PowerSpectrum& transfer_m,
    const ClosedTriangleVectors& vectors,
    const NativeConfig& config);
ComponentResult compute_pre_recon_halo_bias_v1_local_png_1loop_truncated_dfNL(
    const PowerSpectrum& P_L,
    const PowerSpectrum& transfer_m,
    const Triangle& tri,
    const NativeConfig& config,
    const HaloBiasV1Params& bias);
ComponentResult compute_post_recon_halo_bias_v1_local_png_1loop_truncated_dfNL(
    const PowerSpectrum& P_L,
    const PowerSpectrum& transfer_m,
    const Triangle& tri,
    const NativeConfig& config,
    const HaloBiasV1Params& bias);
ComponentResult compute_pre_recon_local_png_1loop_dfNL(
    const PowerSpectrum& P_L,
    const PowerSpectrum& transfer_m,
    const Triangle& tri,
    const NativeConfig& config,
    real b1 = 1.0);
ComponentResult compute_post_recon_local_png_1loop_dfNL(
    const PowerSpectrum& P_L,
    const PowerSpectrum& transfer_m,
    const Triangle& tri,
    const NativeConfig& config,
    real b1 = 1.0);
ComponentResult compute_post_recon_local_png_1loop_dfNL_vectors(
    const PowerSpectrum& P_L,
    const PowerSpectrum& transfer_m,
    const ClosedTriangleVectors& vectors,
    const NativeConfig& config,
    real b1 = 1.0);
ComponentResult compute_pre_recon_local_png_B112II_fNL2_coefficient(
    const PowerSpectrum& P_L,
    const PowerSpectrum& transfer_m,
    const Triangle& tri,
    const NativeConfig& config);
ComponentResult compute_post_recon_local_png_B112II_fNL2_coefficient(
    const PowerSpectrum& P_L,
    const PowerSpectrum& transfer_m,
    const Triangle& tri,
    const NativeConfig& config);
ComponentResult
compute_post_recon_local_png_B112II_fNL2_coefficient_vectors(
    const PowerSpectrum& P_L,
    const PowerSpectrum& transfer_m,
    const ClosedTriangleVectors& vectors,
    const NativeConfig& config);
/*
 * 通过全部隔离诊断后开放的显式 finite-fNL DM 入口：
 *
 * Btotal = B_G_tree + B_G_1loop
 *          + fNL * dBdfNL_local_total
 *          + fNL^2 * B112II_fNL2_coefficient .
 *
 * Btree/B1loop 继续表示 Gaussian 基线，response 与二次系数仍分别保存在
 * 原字段中；因此旧入口及 profiler 所依赖的字段语义保持不变。
 */
ComponentResult compute_pre_recon_local_png_finite_1loop(
    const PowerSpectrum& P_L,
    const PowerSpectrum& transfer_m,
    const Triangle& tri,
    const NativeConfig& config,
    real fNL);
ComponentResult compute_post_recon_local_png_finite_1loop(
    const PowerSpectrum& P_L,
    const PowerSpectrum& transfer_m,
    const Triangle& tri,
    const NativeConfig& config,
    real fNL);

}  // namespace marisa_b_native

#endif  // MARISA_B_NATIVE_H
